<?php
return array (
  'widget_def.birthdays' => 'Today\'s birthdays',
  'widget_def.dbtech_credits_richest' => 'DragonByte Tech: Credits - Richest Users',
  'widget_def.dbtech_credits_wallet' => 'DragonByte Tech: Credits - Wallet',
  'widget_def.find_member' => 'Tìm thành viên',
  'widget_def.forum_statistics' => 'Thống kê diễn đàn',
  'widget_def.html' => 'HTML',
  'widget_def.member_stat' => 'Member stat',
  'widget_def.members_online' => 'Thành viên trực tuyến',
  'widget_def.new_posts' => 'New posts',
  'widget_def.new_profile_posts' => 'New profile posts',
  'widget_def.new_threads' => 'New threads',
  'widget_def.newest_members' => 'Thành viên mới',
  'widget_def.online_statistics' => 'Online statistics',
  'widget_def.php_callback' => 'Hàm PHP',
  'widget_def.share_page' => 'Chia sẻ trang',
  'widget_def.siropu_shoutbox' => 'Shoutbox',
  'widget_def.template_syntax' => 'Template syntax',
  'widget_def.th_most_played_spotify' => '[TH] Spotify: Most Played',
  'widget_def.th_now_playing_spotify' => '[TH] Spotify: Now Playing',
  'widget_def.thread_poll' => 'Thread poll',
  'widget_def.visitor_panel' => 'Bảng khách truy cập',
);